name: analytics_portfolio

profile: analytics_portfolio

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  
  analytics_portfolio:
    staging:
      +materialized: view
    marts:
      +materialized: table
