analytics_portfolio:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_BIGQUERY_PROJECT', 'your-actual-gcp-project-id') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', 'dev_staging') }}"
      keyfile_json: "{{ env_var('GCP_SA_KEY_JSON') }}"
      threads: 4