analytics_portfolio:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT', 'analytics-portfolio-506805') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', 'dev') }}"
      keyfile: "{{ env_var('GCP_SA_KEY_PATH') }}"
      threads: 4