name: dbt Daily & Weekly Refresh

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install dbt-bigquery

      - name: Authenticate to BigQuery
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run dbt
        env:
          IS_SUNDAY: ${{ github.event.schedule == '0 17 * * 0' }}
          GCP_SA_KEY_PATH: ${{ steps.auth.outputs.credentials_file_path }}
          DBT_BIGQUERY_PROJECT: "analytics-portfolio-506805" 
          DBT_BIGQUERY_DATASET: "dev"             
        run: |
          dbt deps --profiles-dir .
          if [ "$IS_SUNDAY" = "true" ]; then
            echo "Running Sunday Full Refresh..."
            dbt run --full-refresh --profiles-dir .
          else
            echo "Running Daily Incremental Run..."
            dbt run --profiles-dir .
          fi